name: End-to-end tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-replayio:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Replay Chromium
      run: npx replayio install

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: replay-chromium
        spec: cypress/e2e/1-getting-started/todo.cy.js
      env:
        REPLAYIO_APIKEY: ${{ secrets.REPLAYIO_APIKEY }}
